### ISSUE TITLE
track_id CLI

### ISSUE THREAD

**Issue by 89z** [acgonzales/pydeezer#16]
Is it possible to download by track_id using the CLI?

**Comment by acgonzales** [comment]
Hi, I haven't implemented that yet and it's a good enhancement for the CLI. I'll work on it if I have the time, thanks.

**Comment by 89z** [comment]
this seems to do as a workaround:

~~~py
import os, pydeezer
arl = os.environ['ARL']
pydeezer.Deezer(arl=arl).get_track('75498415')['download']('.')
~~~
